id: PAD80D4BA
initial_creation_type: input
source_metadata:
  title: Khenchen Ngawang Palzang Series
  language: es
  description: 'Texts by the great Dzogchen master Khenchen Ngawang Palzang (ngag
    dbang dpal bzang, 1879–1941), also known as Khenpo Ngakchung:'
  volume:
    06963373022b44a4aa3569fff322329e:
      title: Seeds of the Four Philosophical Schools
      parent: Buddhist Philosophy
    06571795a547427cbd6c24922750762b:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Dzogchen
    8242c2ef2348454694c7e3ce84f7f1b3:
      title: The Five Wisdoms
      parent: Dzogchen
    381d09f2edee415a9fc6237fab0e8f67:
      title: Prayer to Pema Tötreng Tsal
      parent: Guru Rinpoche Prayers
    24fe1b2306254250a432a3b4d793a93f:
      title: Brief Succession of Lives Prayer
      parent: Prayers
    748011975e144426ab641246e6be9a92:
      title: 'Gyang Lu: A Song of Calling from Afar'
      parent: Prayers
    061df768b2a84c6a8fe059dbf4e24990:
      title: Prayer for this Life, the Next and the Bardos
      parent: Prayers
    1e25f2d6068e4d3e827cf03414421202:
      title: Prayer to Khenpo Ngawang Palzang
      parent: Prayers
    b7feb1e4380b41cc802d8076d2cbe29c:
      title: Brief Homage to the Twenty-One Tārās
      parent: Tārā
created_at: '2022-03-01T00:22:24.758408'
last_modified_at: '2022-03-01T00:22:24.758412'
